### ISSUE TITLE
Interests timing out with App Parameters

### ISSUE THREAD

**Issue by satyaprakash-1729** [zjkmxy/python-ndn#11]
While trying to send NDN interests with Application Parameters the interests are timing out, on the other hand the interests are satisfied when there are no Application Parameters. Even while trying to run rpc_producer and rpc_consumer in the examples of python-ndn the interests are timing out. Is this due to some security issues?

**Comment by zjkmxy** [comment]
There are multiple reasons.
- Interests with Application Parameters are signed by default, so security configuration may be a reason. But it will raises an exception if you do not have a default identity or a default key. I don't think this is the bug.
- The Interest may be dropped by the NFD. I experienced this several times. You can try to enable NFD log and see whether it receives your Interest.

**Comment by satyaprakash-1729** [comment]
> There are multiple reasons.
> 
> * Interests with Application Parameters are signed by default, so security configuration may be a reason. But it will raises an exception if you do not have a default identity or a default key. I don't think this is the bug.
> * The Interest may be dropped by the NFD. I experienced this several times. You can try to enable NFD log and see whether it receives your Interest.

Thank you for your reply. After looking at the NFD logs we found that there was a problem with the serialization procedure which was having trouble recognizing the TLV fields. This was happening because of an older version of NFD not being compatible with the python-ndn module. It was fixed when we updated our code to use the latest NFD commit. Thank you for your help.
