### ISSUE TITLE
NDNApp stuck when after_start() throws exception

### ISSUE THREAD

**Issue by JonnyKong** [zjkmxy/python-ndn#5]
In `NDNApp.run_forever()`, if the `after_start` continuation throws an exception, the event loop might get stuck. I'm opening this issue so that you don't forget.

As we discussed last week, one quick fix is to change:
https://github.com/zjkmxy/python-ndn/blob/16cb6de6537a334ada2e76c2a43b156269edfed3/src/ndn/app.py#L239-L240
to:
```
if after_start:
    try:
        await after_start
    except Exception as exc:
        self.face.shutdown()
        raise exc from None
```

**Comment by zjkmxy** [comment]
Thank you for opening this.
It's fixed on schema branch but not yet on the master.
I will do this ASAP.

https://github.com/zjkmxy/python-ndn/blob/cac66e7818857e633228bfc57c192b6f079419e5/src/ndn/app.py#L236-L244
