### ISSUE TITLE
Shorten Nack encoding

### ISSUE THREAD

**Issue by yoursunny** [zjkmxy/python-ndn#9]
When encoding Nack, only include Name, CanBePrefix, MustBeFresh, ForwardingHint, and Nonce elements of the Interest. Omit other fields.
Change Interest-to-Nack matching functions accordingly.

This change is required by NDNLPv2 protocol change. See [NFD Feature 4535](https://redmine.named-data.net/issues/4535).

**Comment by Pesa** [comment]
FYI we decided to revert this design decision, see https://redmine.named-data.net/issues/4535
